	<?php

	$users = [ 
		['usuario' => 'Guadalupe.Rivera','pwd' => bcrypt('123345'),'nombre' => 'Guadalupe','apepa' => 'Rivera','apema' => '','isadm' => false],
		['usuario' => 'Leopoldo.Mauricio','pwd' => bcrypt('123345'),'nombre' => 'Leopoldo','apepa' => 'Mauricio','apema' => '','isadm' => false],
		['usuario' => 'Paco.Ramire','pwd' => bcrypt('123345'),'nombre' => 'Paco','apepa' => 'Ramire','apema' => '','isadm' => false],
		['usuario' => 'Ernesto.Guevara','pwd' => bcrypt('123345'),'nombre' => 'Ernesto','apepa' => 'Guevara','apema' => '','isadm' => false],
		['usuario' => 'Isai.Lazcan','pwd' => bcrypt('123345'),'nombre' => 'Isai','apepa' => 'Lazcan','apema' => '','isadm' => false],
		['usuario' => 'Luz.Janet','pwd' => bcrypt('123345'),'nombre' => 'Luz','apepa' => 'Janet','apema' => '','isadm' => false],
		['usuario' => 'Aaron.Bernal','pwd' => bcrypt('123345'),'nombre' => 'Aaron','apepa' => 'Bernal','apema' => '','isadm' => false],
		['usuario' => 'Jorge.Torre','pwd' => bcrypt('123345'),'nombre' => 'Jorge','apepa' => 'Torre','apema' => '','isadm' => false],
		['usuario' => 'Jorge.Anaya','pwd' => bcrypt('123345'),'nombre' => 'Jorge','apepa' => 'Anaya','apema' => '','isadm' => false],
		['usuario' => 'Carlos.Ibarra','pwd' => bcrypt('123345'),'nombre' => 'Carlos','apepa' => 'Ibarra','apema' => '','isadm' => false],
		['usuario' => 'Javier.Muñoz','pwd' => bcrypt('123345'),'nombre' => 'Javier','apepa' => 'Muñoz','apema' => '','isadm' => false],
		['usuario' => 'Saira.Lizbeth','pwd' => bcrypt('123345'),'nombre' => 'Saira','apepa' => 'Lizbeth','apema' => '','isadm' => false],
		['usuario' => 'Oscar.Bader','pwd' => bcrypt('123345'),'nombre' => 'Oscar','apepa' => 'Bader','apema' => '','isadm' => false],
		['usuario' => 'Claudia.Del','pwd' => bcrypt('123345'),'nombre' => 'Claudia','apepa' => 'Del','apema' => '','isadm' => false],
		['usuario' => 'Daniela.Cabrera','pwd' => bcrypt('123345'),'nombre' => 'Daniela','apepa' => 'Cabrera','apema' => '','isadm' => false],
		['usuario' => 'Maria.Mirasol','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Mirasol','apema' => '','isadm' => false],
		['usuario' => 'Christian.Paul','pwd' => bcrypt('123345'),'nombre' => 'Christian','apepa' => 'Paul','apema' => '','isadm' => false],
		['usuario' => 'Nadia.de','pwd' => bcrypt('123345'),'nombre' => 'Nadia','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Alejandra.Garcia','pwd' => bcrypt('123345'),'nombre' => 'Alejandra','apepa' => 'Garcia','apema' => '','isadm' => false],
		['usuario' => 'Andres.Martinez','pwd' => bcrypt('123345'),'nombre' => 'Andres','apepa' => 'Martinez','apema' => '','isadm' => false],
		['usuario' => 'Jaime.Cuevas','pwd' => bcrypt('123345'),'nombre' => 'Jaime','apepa' => 'Cuevas','apema' => '','isadm' => false],
		['usuario' => 'Estela.Angelica','pwd' => bcrypt('123345'),'nombre' => 'Estela','apepa' => 'Angelica','apema' => '','isadm' => false],
		['usuario' => 'Isabel.Alvarez','pwd' => bcrypt('123345'),'nombre' => 'Isabel','apepa' => 'Alvarez','apema' => '','isadm' => false],
		['usuario' => 'Eduardo.Flores','pwd' => bcrypt('123345'),'nombre' => 'Eduardo','apepa' => 'Flores','apema' => '','isadm' => false],
		['usuario' => 'Rosalia.Serratos','pwd' => bcrypt('123345'),'nombre' => 'Rosalia','apepa' => 'Serratos','apema' => '','isadm' => false],
		['usuario' => 'Socorro.Siordia','pwd' => bcrypt('123345'),'nombre' => 'Socorro','apepa' => 'Siordia','apema' => '','isadm' => false],
		['usuario' => 'Mayra.Alejand','pwd' => bcrypt('123345'),'nombre' => 'Mayra','apepa' => 'Alejand','apema' => '','isadm' => false],
		['usuario' => 'Oswaldo.Caldera','pwd' => bcrypt('123345'),'nombre' => 'Oswaldo','apepa' => 'Caldera','apema' => '','isadm' => false],
		['usuario' => 'Victor.Sanchez','pwd' => bcrypt('123345'),'nombre' => 'Victor','apepa' => 'Sanchez','apema' => '','isadm' => false],
		['usuario' => 'Minerva.Martinez','pwd' => bcrypt('123345'),'nombre' => 'Minerva','apepa' => 'Martinez','apema' => '','isadm' => false],
		['usuario' => 'Alexis.Rios','pwd' => bcrypt('123345'),'nombre' => 'Alexis','apepa' => 'Rios','apema' => '','isadm' => false],
		['usuario' => 'Jorge.Hernand','pwd' => bcrypt('123345'),'nombre' => 'Jorge','apepa' => 'Hernand','apema' => '','isadm' => false],
		['usuario' => 'Alberto.Gutierrez','pwd' => bcrypt('123345'),'nombre' => 'Alberto','apepa' => 'Gutierrez','apema' => '','isadm' => false],
		['usuario' => 'Jose.Avila','pwd' => bcrypt('123345'),'nombre' => 'Jose','apepa' => 'Avila','apema' => '','isadm' => false],
		['usuario' => 'Araceli.Hernandez','pwd' => bcrypt('123345'),'nombre' => 'Araceli','apepa' => 'Hernandez','apema' => '','isadm' => false],
		['usuario' => 'Sara.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Sara','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'Berenice.Ramirez','pwd' => bcrypt('123345'),'nombre' => 'Berenice','apepa' => 'Ramirez','apema' => '','isadm' => false],
		['usuario' => 'Miguel.Angel','pwd' => bcrypt('123345'),'nombre' => 'Miguel','apepa' => 'Angel','apema' => '','isadm' => false],
		['usuario' => 'Christian.ANI','pwd' => bcrypt('123345'),'nombre' => 'Christian','apepa' => 'ANI','apema' => '','isadm' => false],
		['usuario' => 'Paola.Muñoz','pwd' => bcrypt('123345'),'nombre' => 'Paola','apepa' => 'Muñoz','apema' => '','isadm' => false],
		['usuario' => 'Kenia.Cubian','pwd' => bcrypt('123345'),'nombre' => 'Kenia','apepa' => 'Cubian','apema' => '','isadm' => false],
		['usuario' => 'Rocio.Castañe','pwd' => bcrypt('123345'),'nombre' => 'Rocio','apepa' => 'Castañe','apema' => '','isadm' => false],
		['usuario' => 'Carlos.Mayerste','pwd' => bcrypt('123345'),'nombre' => 'Carlos','apepa' => 'Mayerste','apema' => '','isadm' => false],
		['usuario' => 'Alejandra.Goez','pwd' => bcrypt('123345'),'nombre' => 'Alejandra','apepa' => 'Goez','apema' => '','isadm' => false],
		['usuario' => 'Jazmin.NI','pwd' => bcrypt('123345'),'nombre' => 'Jazmin','apepa' => 'NI','apema' => '','isadm' => false],
		['usuario' => 'Maria.Lucreco','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Lucreco','apema' => '','isadm' => false],
		['usuario' => 'Josue.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Josue','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'MIRIAM.MABEL','pwd' => bcrypt('123345'),'nombre' => 'MIRIAM','apepa' => 'MABEL','apema' => '','isadm' => false],
		['usuario' => 'Fernanda.Eguiarte','pwd' => bcrypt('123345'),'nombre' => 'Fernanda','apepa' => 'Eguiarte','apema' => '','isadm' => false],
		['usuario' => 'Jazmin.Zaldivar','pwd' => bcrypt('123345'),'nombre' => 'Jazmin','apepa' => 'Zaldivar','apema' => '','isadm' => false],
		['usuario' => 'Victor.Hugo','pwd' => bcrypt('123345'),'nombre' => 'Victor','apepa' => 'Hugo','apema' => '','isadm' => false],
		['usuario' => 'Denisse.Vidaño','pwd' => bcrypt('123345'),'nombre' => 'Denisse','apepa' => 'Vidaño','apema' => '','isadm' => false],
		['usuario' => 'Amalia.Suarez','pwd' => bcrypt('123345'),'nombre' => 'Amalia','apepa' => 'Suarez','apema' => '','isadm' => false],
		['usuario' => 'Melissa.Espinoza','pwd' => bcrypt('123345'),'nombre' => 'Melissa','apepa' => 'Espinoza','apema' => '','isadm' => false],
		['usuario' => 'Rocio.Hernand','pwd' => bcrypt('123345'),'nombre' => 'Rocio','apepa' => 'Hernand','apema' => '','isadm' => false],
		['usuario' => 'Manuel.Herrera','pwd' => bcrypt('123345'),'nombre' => 'Manuel','apepa' => 'Herrera','apema' => '','isadm' => false],
		['usuario' => 'Laura.Covarru','pwd' => bcrypt('123345'),'nombre' => 'Laura','apepa' => 'Covarru','apema' => '','isadm' => false],
		['usuario' => 'Irene.Resendi','pwd' => bcrypt('123345'),'nombre' => 'Irene','apepa' => 'Resendi','apema' => '','isadm' => false],
		['usuario' => 'Karlo.Moreno','pwd' => bcrypt('123345'),'nombre' => 'Karlo','apepa' => 'Moreno','apema' => '','isadm' => false],
		['usuario' => 'Brenda.Yolotzin','pwd' => bcrypt('123345'),'nombre' => 'Brenda','apepa' => 'Yolotzin','apema' => '','isadm' => false],
		['usuario' => 'Cesar.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Cesar','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'Priscila.Anai','pwd' => bcrypt('123345'),'nombre' => 'Priscila','apepa' => 'Anai','apema' => '','isadm' => false],
		['usuario' => 'Elizabeth.Delgado','pwd' => bcrypt('123345'),'nombre' => 'Elizabeth','apepa' => 'Delgado','apema' => '','isadm' => false],
		['usuario' => 'Brandon.Gonzalez','pwd' => bcrypt('123345'),'nombre' => 'Brandon','apepa' => 'Gonzalez','apema' => '','isadm' => false],
		['usuario' => 'Fabian.Castillo','pwd' => bcrypt('123345'),'nombre' => 'Fabian','apepa' => 'Castillo','apema' => '','isadm' => false],
		['usuario' => 'Martha.Ordaz','pwd' => bcrypt('123345'),'nombre' => 'Martha','apepa' => 'Ordaz','apema' => '','isadm' => false],
		['usuario' => 'Said.Lara','pwd' => bcrypt('123345'),'nombre' => 'Said','apepa' => 'Lara','apema' => '','isadm' => false],
		['usuario' => 'Erika.Viguera','pwd' => bcrypt('123345'),'nombre' => 'Erika','apepa' => 'Viguera','apema' => '','isadm' => false],
		['usuario' => 'Karina.Pulido','pwd' => bcrypt('123345'),'nombre' => 'Karina','apepa' => 'Pulido','apema' => '','isadm' => false],
		['usuario' => 'Crystal.Mejia','pwd' => bcrypt('123345'),'nombre' => 'Crystal','apepa' => 'Mejia','apema' => '','isadm' => false],
		['usuario' => 'Alejandro.Perea','pwd' => bcrypt('123345'),'nombre' => 'Alejandro','apepa' => 'Perea','apema' => '','isadm' => false],
		['usuario' => 'Luis.Precia','pwd' => bcrypt('123345'),'nombre' => 'Luis','apepa' => 'Precia','apema' => '','isadm' => false],
		['usuario' => 'Benjamin.Torres','pwd' => bcrypt('123345'),'nombre' => 'Benjamin','apepa' => 'Torres','apema' => '','isadm' => false],
		['usuario' => 'Cesar.Barrera','pwd' => bcrypt('123345'),'nombre' => 'Cesar','apepa' => 'Barrera','apema' => '','isadm' => false],
		['usuario' => 'Fernando.FNI','pwd' => bcrypt('123345'),'nombre' => 'Fernando','apepa' => 'FNI','apema' => '','isadm' => false],
		['usuario' => 'Alejandra.Reyes','pwd' => bcrypt('123345'),'nombre' => 'Alejandra','apepa' => 'Reyes','apema' => '','isadm' => false],
		['usuario' => 'Claudia.Ocampo','pwd' => bcrypt('123345'),'nombre' => 'Claudia','apepa' => 'Ocampo','apema' => '','isadm' => false],
		['usuario' => 'Alan.Ayala','pwd' => bcrypt('123345'),'nombre' => 'Alan','apepa' => 'Ayala','apema' => '','isadm' => false],
		['usuario' => 'Guillermo.Rojas','pwd' => bcrypt('123345'),'nombre' => 'Guillermo','apepa' => 'Rojas','apema' => '','isadm' => false],
		['usuario' => 'Juan.Carlos','pwd' => bcrypt('123345'),'nombre' => 'Juan','apepa' => 'Carlos','apema' => '','isadm' => false],
		['usuario' => 'Sara.Sanche','pwd' => bcrypt('123345'),'nombre' => 'Sara','apepa' => 'Sanche','apema' => '','isadm' => false],
		['usuario' => 'Marco.Antonio','pwd' => bcrypt('123345'),'nombre' => 'Marco','apepa' => 'Antonio','apema' => '','isadm' => false],
		['usuario' => 'Diane.Lozano','pwd' => bcrypt('123345'),'nombre' => 'Diane','apepa' => 'Lozano','apema' => '','isadm' => false],
		['usuario' => 'Alexander.Gomez','pwd' => bcrypt('123345'),'nombre' => 'Alexander','apepa' => 'Gomez','apema' => '','isadm' => false],
		['usuario' => 'Victor.Alfonso','pwd' => bcrypt('123345'),'nombre' => 'Victor','apepa' => 'Alfonso','apema' => '','isadm' => false],
		['usuario' => 'Brenda.Triguero','pwd' => bcrypt('123345'),'nombre' => 'Brenda','apepa' => 'Triguero','apema' => '','isadm' => false],
		['usuario' => 'Gretchen.Ivette','pwd' => bcrypt('123345'),'nombre' => 'Gretchen','apepa' => 'Ivette','apema' => '','isadm' => false],
		['usuario' => 'Ruben.Alejand','pwd' => bcrypt('123345'),'nombre' => 'Ruben','apepa' => 'Alejand','apema' => '','isadm' => false],
		['usuario' => 'Martha.Perz','pwd' => bcrypt('123345'),'nombre' => 'Martha','apepa' => 'Perz','apema' => '','isadm' => false],
		['usuario' => 'Francisco.Javier','pwd' => bcrypt('123345'),'nombre' => 'Francisco','apepa' => 'Javier','apema' => '','isadm' => false],
		['usuario' => 'Maria.Ines','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Ines','apema' => '','isadm' => false],
		['usuario' => 'Armando.Aldana','pwd' => bcrypt('123345'),'nombre' => 'Armando','apepa' => 'Aldana','apema' => '','isadm' => false],
		['usuario' => 'Jesus.Castañe','pwd' => bcrypt('123345'),'nombre' => 'Jesus','apepa' => 'Castañe','apema' => '','isadm' => false],
		['usuario' => 'Gildardo.Garcia','pwd' => bcrypt('123345'),'nombre' => 'Gildardo','apepa' => 'Garcia','apema' => '','isadm' => false],
		['usuario' => '.Bl','pwd' => bcrypt('123345'),'nombre' => '','apepa' => 'Bl','apema' => '','isadm' => false],
		['usuario' => 'Victor.Aguayo','pwd' => bcrypt('123345'),'nombre' => 'Victor','apepa' => 'Aguayo','apema' => '','isadm' => false],
		['usuario' => 'Miriam.de','pwd' => bcrypt('123345'),'nombre' => 'Miriam','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Lorena.Briseño','pwd' => bcrypt('123345'),'nombre' => 'Lorena','apepa' => 'Briseño','apema' => '','isadm' => false],
		['usuario' => 'Gerardo.Cornejo','pwd' => bcrypt('123345'),'nombre' => 'Gerardo','apepa' => 'Cornejo','apema' => '','isadm' => false],
		['usuario' => 'Patricio.Cabrera','pwd' => bcrypt('123345'),'nombre' => 'Patricio','apepa' => 'Cabrera','apema' => '','isadm' => false],
		['usuario' => 'Daniel.Hernande','pwd' => bcrypt('123345'),'nombre' => 'Daniel','apepa' => 'Hernande','apema' => '','isadm' => false],
		['usuario' => 'Abraham.Hernadez','pwd' => bcrypt('123345'),'nombre' => 'Abraham','apepa' => 'Hernadez','apema' => '','isadm' => false],
		['usuario' => 'Alejandra.Olivares','pwd' => bcrypt('123345'),'nombre' => 'Alejandra','apepa' => 'Olivares','apema' => '','isadm' => false],
		['usuario' => 'Ana.Sandr','pwd' => bcrypt('123345'),'nombre' => 'Ana','apepa' => 'Sandr','apema' => '','isadm' => false],
		['usuario' => 'Rodrigo.Pareyon ','pwd' => bcrypt('123345'),'nombre' => 'Rodrigo','apepa' => 'Pareyon ','apema' => '','isadm' => false],
		['usuario' => 'Guillermo.Gonzalez','pwd' => bcrypt('123345'),'nombre' => 'Guillermo','apepa' => 'Gonzalez','apema' => '','isadm' => false],
		['usuario' => 'Adrian.Huerta','pwd' => bcrypt('123345'),'nombre' => 'Adrian','apepa' => 'Huerta','apema' => '','isadm' => false],
		['usuario' => 'Cristina.Orozco','pwd' => bcrypt('123345'),'nombre' => 'Cristina','apepa' => 'Orozco','apema' => '','isadm' => false],
		['usuario' => 'Manuel.Medrano','pwd' => bcrypt('123345'),'nombre' => 'Manuel','apepa' => 'Medrano','apema' => '','isadm' => false],
		['usuario' => 'Maria.Guadalu','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Guadalu','apema' => '','isadm' => false],
		['usuario' => 'Arnulfo.Martinez','pwd' => bcrypt('123345'),'nombre' => 'Arnulfo','apepa' => 'Martinez','apema' => '','isadm' => false],
		['usuario' => 'Tania.Resendi','pwd' => bcrypt('123345'),'nombre' => 'Tania','apepa' => 'Resendi','apema' => '','isadm' => false],
		['usuario' => 'Luis.Bernab','pwd' => bcrypt('123345'),'nombre' => 'Luis','apepa' => 'Bernab','apema' => '','isadm' => false],
		['usuario' => 'Luis.Baraja','pwd' => bcrypt('123345'),'nombre' => 'Luis','apepa' => 'Baraja','apema' => '','isadm' => false],
		['usuario' => 'Alberto.Pineda','pwd' => bcrypt('123345'),'nombre' => 'Alberto','apepa' => 'Pineda','apema' => '','isadm' => false],
		['usuario' => 'Claudia.Castañeda','pwd' => bcrypt('123345'),'nombre' => 'Claudia','apepa' => 'Castañeda','apema' => '','isadm' => false],
		['usuario' => 'Esmeralda.Landeros','pwd' => bcrypt('123345'),'nombre' => 'Esmeralda','apepa' => 'Landeros','apema' => '','isadm' => false],
		['usuario' => 'Yarko.S.GNI','pwd' => bcrypt('123345'),'nombre' => 'Yarko','apepa' => 'S.GNI','apema' => '','isadm' => false],
		['usuario' => 'Zayda.Avalos','pwd' => bcrypt('123345'),'nombre' => 'Zayda','apepa' => 'Avalos','apema' => '','isadm' => false],
		['usuario' => 'Celeste.Campos','pwd' => bcrypt('123345'),'nombre' => 'Celeste','apepa' => 'Campos','apema' => '','isadm' => false],
		['usuario' => 'Cynthia.Cervantes','pwd' => bcrypt('123345'),'nombre' => 'Cynthia','apepa' => 'Cervantes','apema' => '','isadm' => false],
		['usuario' => 'Diego.Chavez','pwd' => bcrypt('123345'),'nombre' => 'Diego','apepa' => 'Chavez','apema' => '','isadm' => false],
		['usuario' => 'angeles.Arena','pwd' => bcrypt('123345'),'nombre' => 'angeles','apepa' => 'Arena','apema' => '','isadm' => false],
		['usuario' => 'Daniel.Olaf','pwd' => bcrypt('123345'),'nombre' => 'Daniel','apepa' => 'Olaf','apema' => '','isadm' => false],
		['usuario' => 'Sujey.Adriana','pwd' => bcrypt('123345'),'nombre' => 'Sujey','apepa' => 'Adriana','apema' => '','isadm' => false], 
	];


	$mail_address = [ 
		['email' => 'atnclientesgdl@ph.com.mx',],
		['email' => 'contacto@vincent.com.mx',],
		['email' => 'lapasteria.andares@gmail.com;',],
		['email' => 'andares@chilis.com.mx',],
		['email' => 'andares@sushifactory.com.mx',],
		['email' => 'sbmx38861@starbucks.com.mx',],
		['email' => 'direccion@lamoresca.com',],
		['email' => 'jtorre@almacendelbife.com',],
		['email' => 'facturacion.andares@corazondealcachofa.com',],
		['email' => 'gerenciaandares@gruposon.com',],
		['email' => 'gerenciajuniko@gruposon.com',],
		['email' => 'bdesigualagdl@ph.com.mx',],
		['email' => 'andares@emwa.com.mx',],
		['email' => 'claudia.deltoro@macame.com.mx ',],
		['email' => 'andares@dione.com.mx',],
		['email' => 'vhernandez@grupoodem.com',],
		['email' => 'rapsodia_guadalajara@grupoaxo.com',],
		['email' => 'nadia.delarosa@store.hm.com',],
		['email' => 'baldogdl@ph.com.mx',],
		['email' => 'mbxmxlsandares@levi.com',],
		['email' => 'andares@brantano.com.mx',],
		['email' => 'storemx014@carters.com',],
		['email' => 'andares@oemoda.com',],
		['email' => 'h014@highlife.com.mx',],
		['email' => 'guadalajara16t@adolfodominguez.mx; ',],
		['email' => 'andaresgv@gv.com.mx',],
		['email' => 'arpar75@gmail.com',],
		['email' => 'gdl017@charly.com.mx',],
		['email' => 'guadalajara@kiplingmexico.com.mx',],
		['email' => 'atn_clientes@kauffmanopticas.com.mx',],
		['email' => 'guadalajara-andares.mx@puma.com',],
		['email' => 'jorge.hernandez.martinez.contractor@bbva.com ',],
		['email' => 'alberto.gutierrez@banorte.com',],
		['email' => 's321@typhoonsports.com.mx',],
		['email' => 'mexico_andares@bimbaylola.com',],
		['email' => 'saravlg@mx.inditex.com',],
		['email' => 'ni@ni.com.mx',],
		['email' => 'maribelag@mx.inditex.com',],
		['email' => 'andreinapdp@mx.inditex.com',],
		['email' => 'zapopansf279@elcorteingles.es',],
		['email' => 'guess_andares@grupoaxo.com',],
		['email' => 'guess_andares@grupoaxo.com',],
		['email' => 'bsamsungandgdl@ph.com.mx',],
		['email' => 'shifraspa132@gmail.com',],
		['email' => 'shifraspa132@gmail.com',],
		['email' => 'facturacionmisenandares@gmail.com',],
		['email' => 'josue.lopez@macstore.cloud',],
		['email' => 'santamariaandares@hotmail.com',],
		['email' => 'eguiartef@ae.com ',],
		['email' => 'hollister_andaresgdl@grupoaxo.com',],
		['email' => 'tdaand@adidas.com',],
		['email' => 'melissashoesandaresgdl@gmail.com',],
		['email' => 'contacto@tohhaa.com',],
		['email' => 'tienda29@coqueta.com.mx',],
		['email' => 'ni@ni.com.mx',],
		['email' => 'qss.gua.andares@quiksilvermexico.com',],
		['email' => 'andaresgdl@tous.com',],
		['email' => 'tiendagdlplazaandares@cuadra.com.mx',],
		['email' => 'kmoreno@obsmex.com.mx',],
		['email' => 'Byandalons@liverpool.com.mx',],
		['email' => 'mx.gdl.andares@pandorastores.net',],
		['email' => 'mgr8717@forever-21.com.mx',],
		['email' => 'ckjandares@grupoaxo.com',],
		['email' => 'bgonzalezramirez@levi.com',],
		['email' => 'tkdsandares@grupoaxo.com',],
		['email' => 'bbw_andares@grupoaxo.com',],
		['email' => 'tommy_guadalajaraandares@grupoaxo.com',],
		['email' => 'b.andares.gua@benettonmex.com',],
		['email' => 'brooksbrothers_andares@grupoaxo.com',],
		['email' => 'sephora.andares@sephora.com',],
		['email' => 'vsfa_andares@grupoaxo.com',],
		['email' => 'devlyna311@devlyn.com.mx',],
		['email' => 'gncandareszapgdl@gnc.mx',],
		['email' => 'lushandares@gmail.com',],
		['email' => 'tafandaresgdl@grupoaxo.com',],
		['email' => 'me_shop258@artsana.com',],
		['email' => 'andares@gonvill.com.mx',],
		['email' => 'andares@gonvill.com.mx',],
		['email' => 'andares@gonvill.com.mx',],
		['email' => 'andares@gonvill.com.mx',],
		['email' => 'andares@sevillasol.com.mx',],
		['email' => 'socialpijamasgdl@gmail.com',],
		['email' => 'boutique.plazaandares@domarts.com.mx',],
		['email' => 'andaresgdl@steren.com.mx',],
		['email' => 'huaweiandaresgdl@mobo.com.mx',],
		['email' => 'gerenciaandares@mygtelecom.mx',],
		['email' => 'gretchen.perez@telcel.com',],
		['email' => 'ulises.cornejo@grupocosteno.com',],
		['email' => 'patriceandares@gmail.com',],
		['email' => 'fmiranda@actinver.com.mx',],
		['email' => 'inesdjs_28@hotmail.com',],
		['email' => 'aarmandog@aeromexicoandares.com',],
		['email' => 'truereligionandares@colemx.com; jesusconsulting1@gmail.com',],
		['email' => 'replayandares@colemx.com',],
		['email' => 'ma_andares@bcbg.com.mx',],
		['email' => 'ma_andares@bcbg.com.mx',],
		['email' => 'ildiavolo.andares@gmail.com',],
		['email' => 'lorena.briseno@macame.com.mx',],
		['email' => 'gerardo.cornejo@nespresso.com',],
		['email' => 'patricio.cabrera@nespresso.com; eduardo.Rodriguez1@nespresso.com',],
		['email' => 'andares@palzileri.com.mx',],
		['email' => 'lust_andares@grupoaxo.com',],
		['email' => 'andares@stevemadden.com.mx',],
		['email' => 'louder.andares@gv.com.mx',],
		['email' => 'eduardo.torres@benandfrank.com',],
		['email' => 'talentoandares1@gmail.com',],
		['email' => 'Lamarrestaurant.Andares@gmail.com',],
		['email' => 'bkorsgdl@ph.com.mx',],
		['email' => 'coach_andares@grupoaxo.com',],
		['email' => 'Boss_Black_Store_Andares@shops.hugoboss.com',],
		['email' => 'elizabeth.bocardo@gruposacromonte.com',],
		['email' => 'resendizt@pasteleriasmarisa.com.mx',],
		['email' => 'gte.cj.andares@stargdl.mx',],
		['email' => 'ni@ni.com.mx',],
		['email' => ' albertop@ks6.com.mx',],
		['email' => 'yamile@gruposandys.com',],
		['email' => 'andares@cafelaflordecordoba.com',],
		['email' => 'sunfagdl@gmail.com',],
		['email' => 'andares@pollopepe.com.mx',],
		['email' => 'bkmx3216964@alaparrilla.com',],
		['email' => 'jonathanupnjoy@hotmail.com',],
		['email' => ' <jclariosg@televisa.com.mx>',],
		['email' => 'gdl@enigmarooms.com.mx ',],
		['email' => 'gdl@enigmarooms.com.mx ',],
		['email' => 'cvip_andares_gdl@cinepolis.com',]
	];
	



	$positions = [
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación',
		'Operación', 
	];
	

	$brands = [
		3,
		5,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		15,
		16,
		17,
		18,
		19,
		21,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		33,
		34,
		35,
		36,
		38,
		39,
		40,
		42,
		44,
		45,
		47,
		49,
		50,
		54,
		55,
		55,
		58,
		59,
		59,
		61,
		65,
		65,
		66,
		68,
		72,
		73,
		74,
		75,
		77,
		78,
		79,
		80,
		81,
		82,
		83,
		85,
		86,
		87,
		88,
		90,
		91,
		93,
		94,
		95,
		96,
		97,
		98,
		99,
		101,
		103,
		104,
		105,
		108,
		111,
		111,
		111,
		111,
		112,
		115,
		116,
		118,
		120,
		121,
		122,
		124,
		127,
		128,
		129,
		130,
		132,
		133,
		134,
		134,
		137,
		138,
		139,
		139,
		141,
		142,
		143,
		144,
		146,
		147,
		148,
		149,
		150,
		151,
		155,
		157,
		158,
		161,
		162,
		163,
		167,
		168,
		170,
		173,
		174,
		175,
		176,
		176,
		177
	];
	

	$U = [
		['usuario' => 'Claudia.Elizondo','pwd' => bcrypt('123345'),'nombre' => 'Claudia','apepa' => 'Elizondo','apema' => '','isadm' => false],
		['usuario' => 'Beatriz.Hernandez','pwd' => bcrypt('123345'),'nombre' => 'Beatriz','apepa' => 'Hernandez','apema' => '','isadm' => false],
		['usuario' => 'Maria.Laura','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Laura','apema' => '','isadm' => false],
		['usuario' => 'Angela.Lozano','pwd' => bcrypt('123345'),'nombre' => 'Angela','apepa' => 'Lozano','apema' => '','isadm' => false],
		['usuario' => 'Jhabiv.Leon','pwd' => bcrypt('123345'),'nombre' => 'Jhabiv','apepa' => 'Leon','apema' => '','isadm' => false],
		['usuario' => 'Maria.Jose','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Jose','apema' => '','isadm' => false],
		['usuario' => 'Michele.Durzo','pwd' => bcrypt('123345'),'nombre' => 'Michele','apepa' => 'Durzo','apema' => '','isadm' => false],
		['usuario' => 'Blanca.Gomez','pwd' => bcrypt('123345'),'nombre' => 'Blanca','apepa' => 'Gomez','apema' => '','isadm' => false],
		['usuario' => 'Alejandro.Gonzalez','pwd' => bcrypt('123345'),'nombre' => 'Alejandro','apepa' => 'Gonzalez','apema' => '','isadm' => false],
		['usuario' => 'Polo.Lara','pwd' => bcrypt('123345'),'nombre' => 'Polo','apepa' => 'Lara','apema' => '','isadm' => false],
		['usuario' => 'Cecilia.Leyva','pwd' => bcrypt('123345'),'nombre' => 'Cecilia','apepa' => 'Leyva','apema' => '','isadm' => false],
		['usuario' => 'Michelle.Lomeli','pwd' => bcrypt('123345'),'nombre' => 'Michelle','apepa' => 'Lomeli','apema' => '','isadm' => false],
		['usuario' => 'Julian.Cuevas','pwd' => bcrypt('123345'),'nombre' => 'Julian','apepa' => 'Cuevas','apema' => '','isadm' => false],
		['usuario' => 'Maru.Romero','pwd' => bcrypt('123345'),'nombre' => 'Maru','apepa' => 'Romero','apema' => '','isadm' => false],
		['usuario' => 'Luis.Antoni','pwd' => bcrypt('123345'),'nombre' => 'Luis','apepa' => 'Antoni','apema' => '','isadm' => false],
		['usuario' => 'Liliana.Lozano','pwd' => bcrypt('123345'),'nombre' => 'Liliana','apepa' => 'Lozano','apema' => '','isadm' => false],
		['usuario' => 'Maria.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'Alejandro.Herrera','pwd' => bcrypt('123345'),'nombre' => 'Alejandro','apepa' => 'Herrera','apema' => '','isadm' => false],
		['usuario' => 'Ana.Paula','pwd' => bcrypt('123345'),'nombre' => 'Ana','apepa' => 'Paula','apema' => '','isadm' => false],
		['usuario' => 'Danae.Chavez','pwd' => bcrypt('123345'),'nombre' => 'Danae','apepa' => 'Chavez','apema' => '','isadm' => false],
		['usuario' => 'Barbara.Pulido','pwd' => bcrypt('123345'),'nombre' => 'Barbara','apepa' => 'Pulido','apema' => '','isadm' => false],
		['usuario' => 'Jose.Luis','pwd' => bcrypt('123345'),'nombre' => 'Jose','apepa' => 'Luis','apema' => '','isadm' => false],
		['usuario' => 'Viviana.Cortes','pwd' => bcrypt('123345'),'nombre' => 'Viviana','apepa' => 'Cortes','apema' => '','isadm' => false],
		['usuario' => 'Teresa.de','pwd' => bcrypt('123345'),'nombre' => 'Teresa','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Eulalia.Canudas','pwd' => bcrypt('123345'),'nombre' => 'Eulalia','apepa' => 'Canudas','apema' => '','isadm' => false],
		['usuario' => 'Laura.Estela','pwd' => bcrypt('123345'),'nombre' => 'Laura','apepa' => 'Estela','apema' => '','isadm' => false],
		['usuario' => 'Fernanda.Uriarte','pwd' => bcrypt('123345'),'nombre' => 'Fernanda','apepa' => 'Uriarte','apema' => '','isadm' => false],
		['usuario' => 'Virginie.Dubray','pwd' => bcrypt('123345'),'nombre' => 'Virginie','apepa' => 'Dubray','apema' => '','isadm' => false],
		['usuario' => 'Sergio.de','pwd' => bcrypt('123345'),'nombre' => 'Sergio','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Norberto.de','pwd' => bcrypt('123345'),'nombre' => 'Norberto','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Rafael.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Rafael','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'Carolina.Moran','pwd' => bcrypt('123345'),'nombre' => 'Carolina','apepa' => 'Moran','apema' => '','isadm' => false],
		['usuario' => 'Cristina.Barrileiro','pwd' => bcrypt('123345'),'nombre' => 'Cristina','apepa' => 'Barrileiro','apema' => '','isadm' => false],
		['usuario' => 'Viviana.Cortez','pwd' => bcrypt('123345'),'nombre' => 'Viviana','apepa' => 'Cortez','apema' => '','isadm' => false],
		['usuario' => 'Andrea.Castro','pwd' => bcrypt('123345'),'nombre' => 'Andrea','apepa' => 'Castro','apema' => '','isadm' => false],
		['usuario' => 'Jessica.Nayeli','pwd' => bcrypt('123345'),'nombre' => 'Jessica','apepa' => 'Nayeli','apema' => '','isadm' => false],
		['usuario' => 'Pilar.Ferrer','pwd' => bcrypt('123345'),'nombre' => 'Pilar','apepa' => 'Ferrer','apema' => '','isadm' => false],
		['usuario' => 'ANI.Lisse','pwd' => bcrypt('123345'),'nombre' => 'ANI','apepa' => 'Lisse','apema' => '','isadm' => false],
		['usuario' => 'Maya.Garcia','pwd' => bcrypt('123345'),'nombre' => 'Maya','apepa' => 'Garcia','apema' => '','isadm' => false],
		['usuario' => 'Maurio.Morales','pwd' => bcrypt('123345'),'nombre' => 'Maurio','apepa' => 'Morales','apema' => '','isadm' => false],
		['usuario' => 'Lucrecia.Ramirez','pwd' => bcrypt('123345'),'nombre' => 'Lucrecia','apepa' => 'Ramirez','apema' => '','isadm' => false],
		['usuario' => 'Lizbeth.Valle','pwd' => bcrypt('123345'),'nombre' => 'Lizbeth','apepa' => 'Valle','apema' => '','isadm' => false],
		['usuario' => 'Carlos.Hernande','pwd' => bcrypt('123345'),'nombre' => 'Carlos','apepa' => 'Hernande','apema' => '','isadm' => false],
		['usuario' => 'Adriary.Ortiz','pwd' => bcrypt('123345'),'nombre' => 'Adriary','apepa' => 'Ortiz','apema' => '','isadm' => false],
		['usuario' => 'Edgar.Melo','pwd' => bcrypt('123345'),'nombre' => 'Edgar','apepa' => 'Melo','apema' => '','isadm' => false],
		['usuario' => 'Rocio.Cornejo','pwd' => bcrypt('123345'),'nombre' => 'Rocio','apepa' => 'Cornejo','apema' => '','isadm' => false],
		['usuario' => 'Maria.Ileana','pwd' => bcrypt('123345'),'nombre' => 'Maria','apepa' => 'Ileana','apema' => '','isadm' => false],
		['usuario' => 'Eva.Aceve','pwd' => bcrypt('123345'),'nombre' => 'Eva','apepa' => 'Aceve','apema' => '','isadm' => false],
		['usuario' => 'Romina.Cueva;','pwd' => bcrypt('123345'),'nombre' => 'Romina','apepa' => 'Cueva;','apema' => '','isadm' => false],
		['usuario' => 'Charo.Ordaz','pwd' => bcrypt('123345'),'nombre' => 'Charo','apepa' => 'Ordaz','apema' => '','isadm' => false],
		['usuario' => 'Benjamin.del','pwd' => bcrypt('123345'),'nombre' => 'Benjamin','apepa' => 'del','apema' => '','isadm' => false],
		['usuario' => 'Silvia.Jauregui','pwd' => bcrypt('123345'),'nombre' => 'Silvia','apepa' => 'Jauregui','apema' => '','isadm' => false],
		['usuario' => 'Alfonso.Fuentes','pwd' => bcrypt('123345'),'nombre' => 'Alfonso','apepa' => 'Fuentes','apema' => '','isadm' => false],
		['usuario' => 'Sofia.Vargas','pwd' => bcrypt('123345'),'nombre' => 'Sofia','apepa' => 'Vargas','apema' => '','isadm' => false],
		['usuario' => 'Montserrat.Patiño','pwd' => bcrypt('123345'),'nombre' => 'Montserrat','apepa' => 'Patiño','apema' => '','isadm' => false],
		['usuario' => 'Taide.Daniela','pwd' => bcrypt('123345'),'nombre' => 'Taide','apepa' => 'Daniela','apema' => '','isadm' => false],
		['usuario' => 'Daniela.Rojas','pwd' => bcrypt('123345'),'nombre' => 'Daniela','apepa' => 'Rojas','apema' => '','isadm' => false],
		['usuario' => 'Giovana.Luna','pwd' => bcrypt('123345'),'nombre' => 'Giovana','apepa' => 'Luna','apema' => '','isadm' => false],
		['usuario' => 'Paola.Segura','pwd' => bcrypt('123345'),'nombre' => 'Paola','apepa' => 'Segura','apema' => '','isadm' => false],
		['usuario' => 'Sofia.Arredon','pwd' => bcrypt('123345'),'nombre' => 'Sofia','apepa' => 'Arredon','apema' => '','isadm' => false],
		['usuario' => 'Mar.Cipri','pwd' => bcrypt('123345'),'nombre' => 'Mar','apepa' => 'Cipri','apema' => '','isadm' => false],
		['usuario' => 'Graciela.Miramontes','pwd' => bcrypt('123345'),'nombre' => 'Graciela','apepa' => 'Miramontes','apema' => '','isadm' => false],
		['usuario' => 'Daniel.Cardona','pwd' => bcrypt('123345'),'nombre' => 'Daniel','apepa' => 'Cardona','apema' => '','isadm' => false],
		['usuario' => 'Fabiola.Macias','pwd' => bcrypt('123345'),'nombre' => 'Fabiola','apepa' => 'Macias','apema' => '','isadm' => false],
		['usuario' => 'Gerardo.Bermea','pwd' => bcrypt('123345'),'nombre' => 'Gerardo','apepa' => 'Bermea','apema' => '','isadm' => false],
		['usuario' => 'Mariel.Baez','pwd' => bcrypt('123345'),'nombre' => 'Mariel','apepa' => 'Baez','apema' => '','isadm' => false],
		['usuario' => 'Clarisa.Sanchez','pwd' => bcrypt('123345'),'nombre' => 'Clarisa','apepa' => 'Sanchez','apema' => '','isadm' => false],
		['usuario' => 'Jaramara.Mendoza','pwd' => bcrypt('123345'),'nombre' => 'Jaramara','apepa' => 'Mendoza','apema' => '','isadm' => false],
		['usuario' => 'Andrea.Tejada','pwd' => bcrypt('123345'),'nombre' => 'Andrea','apepa' => 'Tejada','apema' => '','isadm' => false],
		['usuario' => 'Eduardo.Mora','pwd' => bcrypt('123345'),'nombre' => 'Eduardo','apepa' => 'Mora','apema' => '','isadm' => false],
		['usuario' => 'Ana.Luisa','pwd' => bcrypt('123345'),'nombre' => 'Ana','apepa' => 'Luisa','apema' => '','isadm' => false],
		['usuario' => 'Mariana.Martinez','pwd' => bcrypt('123345'),'nombre' => 'Mariana','apepa' => 'Martinez','apema' => '','isadm' => false],
		['usuario' => 'Cristian.Mejia','pwd' => bcrypt('123345'),'nombre' => 'Cristian','apepa' => 'Mejia','apema' => '','isadm' => false],
		['usuario' => 'Rodolfo.Urbina','pwd' => bcrypt('123345'),'nombre' => 'Rodolfo','apepa' => 'Urbina','apema' => '','isadm' => false],
		['usuario' => 'Antonieta.Pinelo','pwd' => bcrypt('123345'),'nombre' => 'Antonieta','apepa' => 'Pinelo','apema' => '','isadm' => false],
		['usuario' => 'Natali.Montero','pwd' => bcrypt('123345'),'nombre' => 'Natali','apepa' => 'Montero','apema' => '','isadm' => false],
		['usuario' => 'Paola.Luna','pwd' => bcrypt('123345'),'nombre' => 'Paola','apepa' => 'Luna','apema' => '','isadm' => false],
		['usuario' => 'Mayra.Perez','pwd' => bcrypt('123345'),'nombre' => 'Mayra','apepa' => 'Perez','apema' => '','isadm' => false],
		['usuario' => 'Denisse.Martinez','pwd' => bcrypt('123345'),'nombre' => 'Denisse','apepa' => 'Martinez','apema' => '','isadm' => false],
		['usuario' => 'Brenda.Huerta','pwd' => bcrypt('123345'),'nombre' => 'Brenda','apepa' => 'Huerta','apema' => '','isadm' => false],
		['usuario' => 'Rodrigo.NI','pwd' => bcrypt('123345'),'nombre' => 'Rodrigo','apepa' => 'NI','apema' => '','isadm' => false],
		['usuario' => 'Karla.Paola','pwd' => bcrypt('123345'),'nombre' => 'Karla','apepa' => 'Paola','apema' => '','isadm' => false],
		['usuario' => 'Alejandro.Garcia','pwd' => bcrypt('123345'),'nombre' => 'Alejandro','apepa' => 'Garcia','apema' => '','isadm' => false],
		['usuario' => 'Daniela.Lopez','pwd' => bcrypt('123345'),'nombre' => 'Daniela','apepa' => 'Lopez','apema' => '','isadm' => false],
		['usuario' => 'Jessica.Ozumbilla','pwd' => bcrypt('123345'),'nombre' => 'Jessica','apepa' => 'Ozumbilla','apema' => '','isadm' => false],
		['usuario' => 'Claudia.Lazcano','pwd' => bcrypt('123345'),'nombre' => 'Claudia','apepa' => 'Lazcano','apema' => '','isadm' => false],
		['usuario' => 'Gabriela.Quirarte;','pwd' => bcrypt('123345'),'nombre' => 'Gabriela','apepa' => 'Quirarte;','apema' => '','isadm' => false],
		['usuario' => 'Victor.Arandas','pwd' => bcrypt('123345'),'nombre' => 'Victor','apepa' => 'Arandas','apema' => '','isadm' => false],
		['usuario' => 'Mauricio.Najar','pwd' => bcrypt('123345'),'nombre' => 'Mauricio','apepa' => 'Najar','apema' => '','isadm' => false],
		['usuario' => 'Camilo.Mendez','pwd' => bcrypt('123345'),'nombre' => 'Camilo','apepa' => 'Mendez','apema' => '','isadm' => false],
		['usuario' => 'Valery.Baigts','pwd' => bcrypt('123345'),'nombre' => 'Valery','apepa' => 'Baigts','apema' => '','isadm' => false],
		['usuario' => 'Ruben.Martnez','pwd' => bcrypt('123345'),'nombre' => 'Ruben','apepa' => 'Martnez','apema' => '','isadm' => false],
		['usuario' => 'Ricardo.de','pwd' => bcrypt('123345'),'nombre' => 'Ricardo','apepa' => 'de','apema' => '','isadm' => false],
		['usuario' => 'Juan.Pedro','pwd' => bcrypt('123345'),'nombre' => 'Juan','apepa' => 'Pedro','apema' => '','isadm' => false],
		['usuario' => 'Juli.-','pwd' => bcrypt('123345'),'nombre' => 'Juli','apepa' => '-','apema' => '','isadm' => false],
		['usuario' => '.An','pwd' => bcrypt('123345'),'nombre' => '','apepa' => 'An','apema' => '','isadm' => false],
		['usuario' => 'Noria.Castro','pwd' => bcrypt('123345'),'nombre' => 'Noria','apepa' => 'Castro','apema' => '','isadm' => false],
		['usuario' => 'Karina.Maribel','pwd' => bcrypt('123345'),'nombre' => 'Karina','apepa' => 'Maribel','apema' => '','isadm' => false],
		['usuario' => '.Ir','pwd' => bcrypt('123345'),'nombre' => '','apepa' => 'Ir','apema' => '','isadm' => false],
		['usuario' => 'Silvestre.Alfaro','pwd' => bcrypt('123345'),'nombre' => 'Silvestre','apepa' => 'Alfaro','apema' => '','isadm' => false],
		['usuario' => 'Karina.Partida','pwd' => bcrypt('123345'),'nombre' => 'Karina','apepa' => 'Partida','apema' => '','isadm' => false],
		['usuario' => 'Schuster.Sabine','pwd' => bcrypt('123345'),'nombre' => 'Schuster','apepa' => 'Sabine','apema' => '','isadm' => false],
		['usuario' => 'Carolina.Rodriguez','pwd' => bcrypt('123345'),'nombre' => 'Carolina','apepa' => 'Rodriguez','apema' => '','isadm' => false],
		['usuario' => 'Andres.Espinosa','pwd' => bcrypt('123345'),'nombre' => 'Andres','apepa' => 'Espinosa','apema' => '','isadm' => false],
		['usuario' => 'Marcos.Vazquez','pwd' => bcrypt('123345'),'nombre' => 'Marcos','apepa' => 'Vazquez','apema' => '','isadm' => false],
		['usuario' => 'Valeria.Liñan','pwd' => bcrypt('123345'),'nombre' => 'Valeria','apepa' => 'Liñan','apema' => '','isadm' => false],
		['usuario' => '.Ya','pwd' => bcrypt('123345'),'nombre' => '','apepa' => 'Ya','apema' => '','isadm' => false],
		['usuario' => 'Mercadotecnia;.Mariana','pwd' => bcrypt('123345'),'nombre' => 'Mercadotecnia;','apepa' => 'Mariana','apema' => '','isadm' => false],
		['usuario' => 'Lidia.Cardern','pwd' => bcrypt('123345'),'nombre' => 'Lidia','apepa' => 'Cardern','apema' => '','isadm' => false],
		['usuario' => 'Zaida.Olivare','pwd' => bcrypt('123345'),'nombre' => 'Zaida','apepa' => 'Olivare','apema' => '','isadm' => false],
		['usuario' => 'Karina.Tabares','pwd' => bcrypt('123345'),'nombre' => 'Karina','apepa' => 'Tabares','apema' => '','isadm' => false],
		['usuario' => 'Cinthya.Cervantes','pwd' => bcrypt('123345'),'nombre' => 'Cinthya','apepa' => 'Cervantes','apema' => '','isadm' => false],
		['usuario' => 'Julio.Cesar','pwd' => bcrypt('123345'),'nombre' => 'Julio','apepa' => 'Cesar','apema' => '','isadm' => false],
		['usuario' => 'DANIEL.GoMEZ','pwd' => bcrypt('123345'),'nombre' => 'DANIEL','apepa' => 'GoMEZ','apema' => '','isadm' => false],
		['usuario' => 'Izamare.Anaya','pwd' => bcrypt('123345'),'nombre' => 'Izamare','apepa' => 'Anaya','apema' => '','isadm' => false],		
	];


	$mail2 = [
		['email' => 'celizondo@ph.com.mx',],
		['email' => 'bhernandez@liverpool.com.mx',],
		['email' => 'marialauracastrom@gmail.com',],
		['email' => 'alozano@cmr.mx',],
		['email' => 'Jhabiv@sushifactory.com.mx',],
		['email' => 'mvelazquez@starbucks.com.mx',],
		['email' => 'micheledurzo68@gmail.com',],
		['email' => 'alberto@almacendelbife.com',],
		['email' => 'alejandrogdp@me.com',],
		['email' => 'operaciones@gruposon.com',],
		['email' => 'cecilia.leyva@loccitane.com',],
		['email' => 'michelle.lomeli@dione.com.mx',],
		['email' => 'jcmentrepreneurs@gmail.com',],
		['email' => 'mromero@grupoodem.com',],
		['email' => 'lstavoli@grupoaxo.com',],
		['email' => 'coordinador.mercadotecnia@brantano.com.mx',],
		['email' => 'maria.lopez@carters.com',],
		['email' => 'eherrera@oemoda.com',],
		['email' => 'anapaula_pintado@piagui.com',],
		['email' => 'dmontes@h-h.com.mx',],
		['email' => 'barbara.pulido@adolfodominguez.com',],
		['email' => 'palancares@gv.com.mx',],
		['email' => 'viviana_cortes@piagui.com',],
		['email' => 'teresapina@charly.com.mx',],
		['email' => 'eulalia@kiplingmexico.com.mx',],
		['email' => 'alberdy@berdico.com.mx',],
		['email' => 'uriartefer@hotmail.com',],
		['email' => 'virginie.dubray@puma.com',],
		['email' => 'sergio.delavega@bbva.com',],
		['email' => 'norberto.sanchez.solano@banorte.com',],
		['email' => 'rafael.lopez@typhoonmx.com',],
		['email' => 'cmoran@ph.com.mx',],
		['email' => 'cbarrileiro@bimbaylola.com',],
		['email' => 'viviana_cortes@piagui.com',],
		['email' => 'bcastro@liverpool.com.mx',],
		['email' => 'jcampos@grupoaxo.com',],
		['email' => 'pferrer@mx.estee.com',],
		['email' => 'avalle@ph.com.mx',],
		['email' => 'juancarlos.mejia@loreal.com',],
		['email' => 'shifraspa132@gmail.com',],
		['email' => ' misenandares@yahoo.com',],
		['email' => 'avalle@ph.com.mx',],
		['email' => 'carlos.hernandez@macstore.mx',],
		['email' => 'ortizad@ae.com; mandujanoM@ae.com',],
		['email' => 'edgar.octavio.melo@adidas-group.com',],
		['email' => 'storemanager@ebrands.com.mx',],
		['email' => 'inoriega@prodigy.net.mx',],
		['email' => 'imagenzapaterias@coqueta.com.mx',],
		['email' => 'romiq@yahoo.com',],
		['email' => 'mercadotecniatiendas@cuadra.com.mx',],
		['email' => 'bdelrazo@birkenstockmexico.com',],
		['email' => 'sjauregui@obsmex.com.mx',],
		['email' => 'jazavalaf@liverpool.com.mx>',],
		['email' => 'svargas@pandora.net',],
		['email' => 'montserrat.patino@forever-21.com.mx',],
		['email' => ' tvekris@grupoaxo.com; ',],
		['email' => 'drojasc@grupoaxo.com',],
		['email' => 'gluna@grupoaxo.com',],
		['email' => 'paola.segura@benettonmex.com',],
		['email' => 'sarredondo@grupoaxo.com',],
		['email' => 'mar.cipriano@sephora.com',],
		['email' => ' gmiramontes@grupoaxo.com',],
		['email' => ' daniel.cardona@mx.sunglasshut.com',],
		['email' => 'fmacias@devlyn.com.mx',],
		['email' => 'bermeamenchaca@gmail.com',],
		['email' => 'mbaez@gnc.com.mx',],
		['email' => 'clarissa.lushmx@gmail.com',],
		['email' => 'jaramara@tatei.com',],
		['email' => 'Andrea.Tejeda@artsana.com',],
		['email' => 'marketing@nix.com.mx',],
		['email' => 'amolina@juguetron.mx',],
		['email' => 'mkt3@gonvill.com.mx',],
		['email' => 'cristian_mejia@mail.com',],
		['email' => 'rodolfo.urbina@gameplanet.com',],
		['email' => 'antonieta@fina-estampa.com',],
		['email' => ' natali.montero@converse.com.mx',],
		['email' => 'pluna@mobo.mx',],
		['email' => 'mayra.perez@steren.com.mx',],
		['email' => 'denisse.martinez.espinosa@huawei.com',],
		['email' => 'b.huerta@mygtelecom.mx',],
		['email' => 'ni@ni.com',],
		['email' => 'karce@actinver.com.mx',],
		['email' => 'macalexgarcia@gmail.com',],
		['email' => 'dlopez@aeromexicoandares.com',],
		['email' => 'jozumbilla@bcbg.com.mx',],
		['email' => 'merca.grupopasta@gmail.com',],
		['email' => 'gabriela.quirarte@nespersso.com',],
		['email' => 'andares@hackett.com',],
		['email' => 'sistemas@palzileri.com.mx',],
		['email' => 'jcmendez@grupoaxo.com',],
		['email' => 'valerybaigts@stevemadden.com.mx',],
		['email' => 'rubenm@gv.com.mx',],
		['email' => 'ricardo.delahuerta@benandfrank.com',],
		['email' => 'jpgf96@me.com',],
		['email' => 'Lamarrestaurant.Andares@gmail.com',],
		['email' => 'aborrego@ph.com.mx',],
		['email' => ' ncastrot@grupoaxo.com',],
		['email' => 'Karina_Gil@hugoboss.com',],
		['email' => 'gabriela.barrera@ggv.mx',],
		['email' => 'silvestre.alfaro@innovasport.com',],
		['email' => 'kpartida@stargdl.mx',],
		['email' => 'schuster.sabine@gmail.com',],
		['email' => 'Carolina.Rodriguez@prb.com.mx',],
		['email' => 'andres@ks6.com.mx',],
		['email' => 'mvazquez@gruposandys.com',],
		['email' => 'mercadotecnia@cafelaflordecordoba.com',],
		['email' => 'sunfagdl@gmail.com',],
		['email' => 'mercadotecnia@pollopepe.com.mx',],
		['email' => 'lidia@qin.mx; vmartinez@qin.mx',],
		['email' => 'franquicias@thesushiandsaladsco.com',],
		['email' => 'karina.tabares@alsea.com.mx',],
		['email' => ' cinthya.cervantes@inoplay.com',],
		['email' => 'jmendozaal@televisa.com.mx',],
		['email' => 'daniel@enigmarooms.com.mx',],
		['email' => 'cvip_andares_gdl@cinepolis.com',],			
	];

	$brands2 = [
		3,
		4,
		6,
		8,
		9,
		10,
		12,
		13,
		16,
		17,
		21,
		22,
		23,
		24,
		25,
		29,
		30,
		31,
		33,
		34,
		35,
		36,
		38,
		39,
		40,
		41,
		42,
		43,
		45,
		46,
		48,
		49,
		50,
		58,
		59,
		60,
		61,
		62,
		64,
		66,
		67,
		68,
		69,
		74,
		76,
		78,
		79,
		80,
		83,
		84,
		85,
		86,
		87,
		88,
		89,
		91,
		95,
		96,
		97,
		98,
		99,
		100,
		101,
		102,
		103,
		104,
		105,
		107,
		109,
		110,
		111,
		112,
		113,
		114,
		115,
		117,
		118,
		119,
		121,
		122,
		125,
		129,
		130,
		131,
		135,
		138,
		140,
		141,
		142,
		143,
		144,
		145,
		147,
		148,
		149,
		150,
		151,
		152,
		153,
		154,
		159,
		160,
		162,
		163,
		164,
		168,
		169,
		171,
		172,
		173,
		174,
		175,
		176,
		177,
		178,			
	];